- name: Test skel
  hosts: localhost
  tasks:

    - name: Success skel
      skel:
      register: skel

    - name: Debug Success
      debug:
        var: skel

    - name: Fail skel
      skel:
        fail: true
      register: skel
      ignore_errors: true

